# circleci/config.yml
version: 2

jobs:
  build:
    docker:                              # CircleCI tags: https://circleci.com/docs/2.0/docker-image-tags.json
      - image: circleci/node:10-browsers # Node tags: https://nodejs.org/en/download/releases/
        environment:
          JOBS: 1 # https://github.com/emberjs/ember.js/issues/15641

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn global add ember-cli
            yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: |
            ./node_modules/ember-cli/bin/ember --version --verbose
            yarn lint:js
            yarn test
            yarn coverage
